In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

In [2]:
bp = pd.read_csv('bp.csv')

In [3]:
#get zipcode list and corresponding counts
zipcode_list = []
for i in range(len(bp)):
    zipcode = bp['Zipcode'][i]
    if zipcode not in zipcode_list:
        zipcode_list.append(zipcode)
zipcode_list.remove('98109-5210')
zipcode_counts = pd.DataFrame()
zipcode_counts['Zipcode'] = zipcode_list
counts_list = []
for i in zipcode_list:
    counts = len(bp[bp['Zipcode'] == i])
    counts_list.append(counts)
zipcode_counts['TOTAL'] = counts_list

In [4]:
category = ['MULTIFAMILY','SINGLE FAMILY / DUPLEX','COMMERCIAL','INSTITUTIONAL','INDUSTRIAL']

for i in category:
    bp_cat = bp[bp['Category'] == i]
    cat_counts_list = []
    for j in zipcode_list:
        cat_counts = len(bp_cat[bp_cat['Zipcode'] == j])
        cat_counts_list.append(cat_counts)
    zipcode_counts['%s' % i] = cat_counts_list

In [5]:
zipcode_counts

,Zipcode,TOTAL,MULTIFAMILY,SINGLE FAMILY / DUPLEX,COMMERCIAL,INSTITUTIONAL,INDUSTRIAL
0,98122,443,88,208,117,30,0
1,98199,393,26,336,21,5,5
2,98119,386,74,227,76,4,5
3,98191,4,0,0,4,0,0
4,98109,490,62,136,280,9,3
5,98107,433,79,232,106,8,8
6,98112,423,51,334,33,5,0
7,98144,482,85,327,58,8,4
8,98102,253,91,121,39,2,0
9,98105,446,51,289,87,19,0
10,98121,180,26,8,146,0,0
11,98125,287,18,221,37,11,0
12,98133,165,26,87,49,1,2
13,98118,471,109,316,35,9,2
14,98116,357,50,259,43,4,1
15,98126,288,43,204,33,7,1
16,98136,246,23,212,9,2,0
17,98101,287,14,2,260,11,0
18,98103,652,82,466,89,15,0
19,98115,604,49,476,69,9,1
20,98177,110,1,106,2,1,0
21,98117,488,33,425,24,6,0
22,98106,208,23,147,28,2,8
23,98104,262,22,9,216,13,2
24,98108,445,24,301,96,7,17
25,98134,141,0,2,108,1,30
26,98146,47,3,44,0,0,0
27,98195,16,0,0,2,13,1
28,98178,42,0,42,0,0,0
29,98033,4,0,0,2,2,0
30,98181,16,2,1,13,0,0
31,98113,2,0,0,1,1,0
32,98154,10,0,0,10,0,0
33,98174,9,1,0,8,0,0
34,98161,2,0,0,2,0,0
35,55418,1,0,1,0,0,0
36,66617,1,0,1,0,0,0
37,35601,1,1,0,0,0,0
38,96816,3,0,1,1,1,0
39,98155,1,0,0,1,0,0
40,33712,1,0,0,1,0,0
41,98164,2,0,0,2,0,0
42,98015,1,0,0,1,0,0
43,95820,1,1,0,0,0,0

In [6]:
zipcode_counts['Zipcode'] = zipcode_counts['Zipcode'].astype(int)

In [7]:
type(zipcode_counts['Zipcode'][4])

numpy.int64

In [8]:
zipcode_counts.to_csv('Zipcode_counts.csv',index=False)